import pynput.keyboard

Ctrls_combinitions = {'\x01': 'Ctrl + a',
            '\x02': 'Ctrl + b',
            '\x03': 'Ctrl + c',
            '\x04': 'Ctrl + d',
            '\x05': 'Ctrl + e',
            '\x06': 'Ctrl + f',
            '\x07': 'Ctrl + g',
            '\x08': 'Ctrl + h',
            '\t': 'Ctrl + i',
            '\n': 'Ctrl + j',
            '\x0b': 'Ctrl + k',
            '\x0c': 'Ctrl + l',
            '\r': 'Ctrl + m',
            '\x0e': 'Ctrl + n',
            '\x0f': 'Ctrl + o',
            '\x10': 'Ctrl + p',
            '\x11': 'Ctrl + q',
            '\x12': 'Ctrl + r',
            '\x13': 'Ctrl + s',
            '\x14': 'Ctrl + t',
            '\x15': 'Ctrl + u',
            '\x16': 'Ctrl + v',
            '\x17': 'Ctrl + w',
            '\x18': 'Ctrl + x',
            '\x1': 'Ctrl + y',
            '\x1a': 'Ctrl + z'}

print('\11' == '')