class Keyboard:
    def __init__(self):
        pass

    keyboard_keys = \
        {
            '0': {'button': '0', 'description': 'Insert 0 character (0)', 'type': 'Number'},
            '1': {'button': '1', 'description': 'Insert 1 character (1)', 'type': 'Number'},
            '2': {'button': '2', 'description': 'Insert 2 character (2)', 'type': 'Number'},
            '3': {'button': '3', 'description': 'Insert 3 character (3)', 'type': 'Number'},
            '4': {'button': '4', 'description': 'Insert 4 character (4)', 'type': 'Number'},
            '5': {'button': '5', 'description': 'Insert 5 character (5)', 'type': 'Number'},
            '6': {'button': '6', 'description': 'Insert 6 character (6)', 'type': 'Number'},
            '7': {'button': '7', 'description': 'Insert 7 character (7)', 'type': 'Number'},
            '8': {'button': '8', 'description': 'Insert 8 character (8)', 'type': 'Number'},
            '9': {'button': '9', 'description': 'Insert 9 character (9)', 'type': 'Number'},
            'A': {'button': 'A', 'description': 'Insert A character (A)', 'type': 'Letter'},
            'B': {'button': 'B', 'description': 'Insert B character (B)', 'type': 'Letter'},
            'C': {'button': 'C', 'description': 'Insert C character (C)', 'type': 'Letter'},
            'D': {'button': 'D', 'description': 'Insert D character (D)', 'type': 'Letter'},
            'E': {'button': 'E', 'description': 'Insert E character (E)', 'type': 'Letter'},
            'F': {'button': 'F', 'description': 'Insert F character (F)', 'type': 'Letter'},
            'G': {'button': 'G', 'description': 'Insert G character (G)', 'type': 'Letter'},
            'H': {'button': 'H', 'description': 'Insert H character (H)', 'type': 'Letter'},
            'I': {'button': 'I', 'description': 'Insert I character (I)', 'type': 'Letter'},
            'J': {'button': 'J', 'description': 'Insert J character (J)', 'type': 'Letter'},
            'K': {'button': 'K', 'description': 'Insert K character (K)', 'type': 'Letter'},
            'L': {'button': 'L', 'description': 'Insert L character (L)', 'type': 'Letter'},
            'M': {'button': 'M', 'description': 'Insert M character (M)', 'type': 'Letter'},
            'N': {'button': 'N', 'description': 'Insert N character (N)', 'type': 'Letter'},
            'O': {'button': 'O', 'description': 'Insert O character (O)', 'type': 'Letter'},
            'P': {'button': 'P', 'description': 'Insert P character (P)', 'type': 'Letter'},
            'Q': {'button': 'Q', 'description': 'Insert Q character (Q)', 'type': 'Letter'},
            'R': {'button': 'R', 'description': 'Insert R character (R)', 'type': 'Letter'},
            'S': {'button': 'S', 'description': 'Insert S character (S)', 'type': 'Letter'},
            'T': {'button': 'T', 'description': 'Insert T character (T)', 'type': 'Letter'},
            'U': {'button': 'U', 'description': 'Insert U character (U)', 'type': 'Letter'},
            'V': {'button': 'V', 'description': 'Insert V character (V)', 'type': 'Letter'},
            'W': {'button': 'W', 'description': 'Insert W character (W)', 'type': 'Letter'},
            'X': {'button': 'X', 'description': 'Insert X character (X)', 'type': 'Letter'},
            'Y': {'button': 'Y', 'description': 'Insert Y character (Y)', 'type': 'Letter'},
            'Z': {'button': 'Z', 'description': 'Insert Z character (Z)', 'type': 'Letter'},
            'a': {'button': 'a', 'description': 'Insert a character (a)', 'type': 'Letter'},
            'b': {'button': 'b', 'description': 'Insert b character (b)', 'type': 'Letter'},
            'c': {'button': 'c', 'description': 'Insert c character (c)', 'type': 'Letter'},
            'd': {'button': 'd', 'description': 'Insert d character (d)', 'type': 'Letter'},
            'e': {'button': 'e', 'description': 'Insert e character (e)', 'type': 'Letter'},
            'f': {'button': 'f', 'description': 'Insert f character (f)', 'type': 'Letter'},
            'g': {'button': 'g', 'description': 'Insert g character (g)', 'type': 'Letter'},
            'h': {'button': 'h', 'description': 'Insert h character (h)', 'type': 'Letter'},
            'i': {'button': 'i', 'description': 'Insert i character (i)', 'type': 'Letter'},
            'j': {'button': 'j', 'description': 'Insert j character (j)', 'type': 'Letter'},
            'k': {'button': 'k', 'description': 'Insert k character (k)', 'type': 'Letter'},
            'l': {'button': 'l', 'description': 'Insert l character (l)', 'type': 'Letter'},
            'm': {'button': 'm', 'description': 'Insert m character (m)', 'type': 'Letter'},
            'n': {'button': 'n', 'description': 'Insert n character (n)', 'type': 'Letter'},
            'o': {'button': 'o', 'description': 'Insert o character (o)', 'type': 'Letter'},
            'p': {'button': 'p', 'description': 'Insert p character (p)', 'type': 'Letter'},
            'q': {'button': 'q', 'description': 'Insert q character (q)', 'type': 'Letter'},
            'r': {'button': 'r', 'description': 'Insert r character (r)', 'type': 'Letter'},
            's': {'button': 's', 'description': 'Insert s character (s)', 'type': 'Letter'},
            't': {'button': 't', 'description': 'Insert t character (t)', 'type': 'Letter'},
            'u': {'button': 'u', 'description': 'Insert u character (u)', 'type': 'Letter'},
            'v': {'button': 'v', 'description': 'Insert v character (v)', 'type': 'Letter'},
            'w': {'button': 'w', 'description': 'Insert w character (w)', 'type': 'Letter'},
            'x': {'button': 'x', 'description': 'Insert x character (x)', 'type': 'Letter'},
            'y': {'button': 'y', 'description': 'Insert y character (y)', 'type': 'Letter'},
            'z': {'button': 'z', 'description': 'Insert z character (z)', 'type': 'Letter'},
            ' ': {'button': ' ', 'description': 'Insert space character (Space)', 'type': 'Button'},
            '~': {'button': '~', 'description': 'Insert ~ character (~)', 'type': 'Punctuation'},
            '`': {'button': '`', 'description': 'Insert ` character (`)', 'type': 'Punctuation'},
            '!': {'button': '!', 'description': 'Insert ! character (exclamation)', 'type': 'Punctuation'},
            '@': {'button': '@', 'description': 'Insert @ character (at)', 'type': 'Punctuation'},
            '#': {'button': '#', 'description': 'Insert # character (hash)', 'type': 'Punctuation'},
            '$': {'button': '$', 'description': 'Insert $ character (dollar)', 'type': 'Punctuation'},
            '%': {'button': '%', 'description': 'Insert % character (percentage)', 'type': 'Punctuation'},
            '^': {'button': '^', 'description': 'Insert ^ character (jump up)', 'type': 'Punctuation'},
            '&': {'button': '&', 'description': 'Insert & character (and)', 'type': 'Punctuation'},
            '*': {'button': '*', 'description': 'Insert * character (asterisk)', 'type': 'Punctuation'},
            '(': {'button': '(', 'description': 'Insert ( character (left circle bracket)', 'type': 'Punctuation'},
            ')': {'button': ')', 'description': 'Insert ) character (right circle bracket)', 'type': 'Punctuation'},
            '_': {'button': '_', 'description': 'Insert _ character (underscore)', 'type': 'Punctuation'},
            '-': {'button': '-', 'description': 'Insert - character (dash)', 'type': 'Punctuation'},
            '+': {'button': '+', 'description': 'Insert + character (plus)', 'type': 'Punctuation'},
            '=': {'button': '=', 'description': 'Insert = character (equal)', 'type': 'Punctuation'},
            '{': {'button': '{', 'description': 'Insert { character (left curly bracket)', 'type': 'Punctuation'},
            '[': {'button': '[', 'description': 'Insert [ character (left square bracket)', 'type': 'Punctuation'},
            ']': {'button': ']', 'description': 'Insert ] character (right square bracket)', 'type': 'Punctuation'},
            '}': {'button': '}', 'description': 'Insert } character (right curly bracket)', 'type': 'Punctuation'},
            '\\': {'button': '\\', 'description': 'Insert \ character (backward slash)', 'type': 'Punctuation'},
            '|': {'button': '|', 'description': 'Insert | character (pipe)', 'type': 'Punctuation'},
            '"': {'button': '"', 'description': 'Insert " character (double quotation)', 'type': 'Punctuation'},
            "'": {'button': "'", 'description': "Insert ' character (single quotation)", 'type': 'Punctuation'},
            ':': {'button': ':', 'description': 'Insert : character (colon)', 'type': 'Punctuation'},
            ';': {'button': ';', 'description': 'Insert ; character (semicolon)', 'type': 'Punctuation'},
            '?': {'button': '?', 'description': 'Insert ? character (question)', 'type': 'Punctuation'},
            '/': {'button': '/', 'description': 'Insert / character (forward slash)', 'type': 'Punctuation'},
            '>': {'button': '>', 'description': 'Insert > character (right arrow)', 'type': 'Punctuation'},
            '.': {'button': '.', 'description': 'Insert . character (dot)', 'type': 'Punctuation'},
            '<': {'button': '<', 'description': 'Insert < character (left arrow)', 'type': 'Punctuation'},
            ',': {'button': ',', 'description': 'Insert , character (comma)', 'type': 'Punctuation'},
            'accept': {'button': 'accept', 'description': 'Press (accept) button on keyboard', 'type':'Button'},
            'add': {'button': 'add', 'description': 'Press (add) button on keyboard', 'type':'Button'},
            'alt': {'button': 'alt', 'description': 'Press (alt) button on keyboard', 'type':'Button'},
            'Key.alt_l': {'button': 'altleft', 'description': 'Press (altleft) button on keyboard', 'type':'Button'},
            'Key.alt_r': {'button': 'altright', 'description': 'Press (altright) button on keyboard', 'type':'Button'},
            'apps': {'button': 'apps', 'description': 'Press (apps) button on keyboard', 'type':'Button'},
            'Key.backspace': {'button': 'backspace', 'description': 'Press (backspace) button on keyboard', 'type':'Button'},
            'browserback': {'button': 'browserback', 'description': 'Press (browserback) button on keyboard', 'type':'Button'},
            'browserfavorites': {'button': 'browserfavorites', 'description': 'Press (browserfavorites) button on keyboard', 'type':'Button'},
            'browserforward': {'button': 'browserforward', 'description': 'Press (browserforward) button on keyboard', 'type':'Button'},
            'browserhome': {'button': 'browserhome', 'description': 'Press (browserhome) button on keyboard', 'type':'Button'},
            'browserrefresh': {'button': 'browserrefresh', 'description': 'Press (browserrefresh) button on keyboard', 'type':'Button'},
            'browsersearch': {'button': 'browsersearch', 'description': 'Press (browsersearch) button on keyboard', 'type':'Button'},
            'browserstop': {'button': 'browserstop', 'description': 'Press (browserstop) button on keyboard', 'type':'Button'},
            'Key.caps_lock': {'button': 'capslock', 'description': 'Press (capslock) button on keyboard', 'type':'Button'},
            'clear': {'button': 'clear', 'description': 'Press (clear) button on keyboard', 'type':'Button'},
            'convert': {'button': 'convert', 'description': 'Press (convert) button on keyboard', 'type':'Button'},
            'Key.ctrl': {'button': 'ctrl', 'description': 'Press (ctrl) button on keyboard', 'type':'Button'},
            'Key.ctrl_l': {'button': 'ctrlleft', 'description': 'Press (ctrlleft) button on keyboard', 'type':'Button'},
            'Key.ctrl_r': {'button': 'ctrlright', 'description': 'Press (ctrlright) button on keyboard', 'type':'Button'},
            'decimal': {'button': 'decimal', 'description': 'Press (decimal) button on keyboard', 'type':'Button'},
            'del': {'button': 'del', 'description': 'Press (del) button on keyboard', 'type':'Button'},
            'Key.delete': {'button': 'delete', 'description': 'Press (delete) button on keyboard', 'type':'Button'},
            'divide': {'button': 'divide', 'description': 'Press (divide) button on keyboard', 'type':'Button'},
            'Key.down': {'button': 'down', 'description': 'Press (down) button on keyboard', 'type':'Button'},
            'Key.end': {'button': 'end', 'description': 'Press (end) button on keyboard', 'type':'Button'},
            'Key.enter': {'button': 'enter', 'description': 'Press (enter) button on keyboard', 'type':'Button'},
            'escape': {'button': 'escape', 'description': 'Press (escape) button on keyboard', 'type':'Button'},
            'execute': {'button': 'execute', 'description': 'Press (execute) button on keyboard', 'type':'Button'},
            'Key.esc': {'button': 'esc', 'description': 'Press (esc) button on keyboard', 'type':'Button'},
            'Key.f1': {'button': 'f1', 'description': 'Press (f1) button on keyboard', 'type':'Function'},
            'Key.f2': {'button': 'f2', 'description': 'Press (f2) button on keyboard', 'type':'Function'},
            'Key.f3': {'button': 'f3', 'description': 'Press (f3) button on keyboard', 'type':'Function'},
            'Key.f4': {'button': 'f4', 'description': 'Press (f4) button on keyboard', 'type':'Function'},
            'Key.f5': {'button': 'f5', 'description': 'Press (f5) button on keyboard', 'type':'Function'},
            'Key.f6': {'button': 'f6', 'description': 'Press (f6) button on keyboard', 'type':'Function'},
            'Key.f7': {'button': 'f7', 'description': 'Press (f7) button on keyboard', 'type':'Function'},
            'Key.f8': {'button': 'f8', 'description': 'Press (f8) button on keyboard', 'type':'Function'},
            'Key.f9': {'button': 'f9', 'description': 'Press (f9) button on keyboard', 'type':'Function'},
            'Key.f10': {'button': 'f10', 'description': 'Press (f10) button on keyboard', 'type':'Function'},
            'Key.f11': {'button': 'f11', 'description': 'Press (f11) button on keyboard', 'type':'Function'},
            'Key.f12': {'button': 'f12', 'description': 'Press (f12) button on keyboard', 'type':'Function'},
            'Key.f13': {'button': 'f13', 'description': 'Press (f13) button on keyboard', 'type':'Function'},
            'Key.f14': {'button': 'f14', 'description': 'Press (f14) button on keyboard', 'type':'Function'},
            'Key.f15': {'button': 'f15', 'description': 'Press (f15) button on keyboard', 'type':'Function'},
            'Key.f16': {'button': 'f16', 'description': 'Press (f16) button on keyboard', 'type':'Function'},
            'Key.f17': {'button': 'f17', 'description': 'Press (f17) button on keyboard', 'type':'Function'},
            'Key.f18': {'button': 'f18', 'description': 'Press (f18) button on keyboard', 'type':'Function'},
            'Key.f19': {'button': 'f19', 'description': 'Press (f19) button on keyboard', 'type':'Function'},
            'Key.f20': {'button': 'f20', 'description': 'Press (f20) button on keyboard', 'type':'Function'},
            'Key.f21': {'button': 'f21', 'description': 'Press (f21) button on keyboard', 'type':'Function'},
            'Key.f22': {'button': 'f22', 'description': 'Press (f22) button on keyboard', 'type':'Function'},
            'Key.f23': {'button': 'f23', 'description': 'Press (f23) button on keyboard', 'type':'Function'},
            'Key.f24': {'button': 'f24', 'description': 'Press (f24) button on keyboard', 'type':'Function'},
            'prtsc': {'button': 'prtsc', 'description': 'Press (prtsc) button on keyboard', 'type':'Button'},
            'prtscr': {'button': 'prtscr', 'description': 'Press (prtscr) button on keyboard', 'type':'Button'},
            'Key.scroll_lock': {'button': 'scrolllock', 'description': 'Press (scrolllock) button on keyboard', 'type':'Button'},
            'num0': {'button': 'num0', 'description': 'Press (num0) button on keyboard', 'type':'Number'},
            'num1': {'button': 'num1', 'description': 'Press (num1) button on keyboard', 'type':'Number'},
            'num2': {'button': 'num2', 'description': 'Press (num2) button on keyboard', 'type':'Number'},
            'num3': {'button': 'num3', 'description': 'Press (num3) button on keyboard', 'type':'Number'},
            'num4': {'button': 'num4', 'description': 'Press (num4) button on keyboard', 'type':'Number'},
            'num5': {'button': 'num5', 'description': 'Press (num5) button on keyboard', 'type':'Number'},
            'num6': {'button': 'num6', 'description': 'Press (num6) button on keyboard', 'type':'Number'},
            'num7': {'button': 'num7', 'description': 'Press (num7) button on keyboard', 'type':'Number'},
            'num8': {'button': 'num8', 'description': 'Press (num8) button on keyboard', 'type':'Number'},
            'num9': {'button': 'num9', 'description': 'Press (num9) button on keyboard', 'type':'Number'},
            'Key.home': {'button': 'home', 'description': 'Press (home) button on keyboard', 'type':'Button'},
            'Key.menu': {'button': 'menu', 'description': 'Press (menu) button on keyboard', 'type':'Button'},
            'Key.insert': {'button': 'insert', 'description': 'Press (insert) button on keyboard', 'type':'Button'},
            'final': {'button': 'final', 'description': 'Press (final) button on keyboard', 'type':'Button'},
            'fn': {'button': 'fn', 'description': 'Press (fn) button on keyboard', 'type':'Button'},
            'Key.left': {'button': 'left', 'description': 'Press (left) button on keyboard', 'type':'Button'},
            'launchapp1': {'button': 'launchapp1', 'description': 'Press (launchapp1) button on keyboard', 'type':'Button'},
            'launchapp2': {'button': 'launchapp2', 'description': 'Press (launchapp2) button on keyboard', 'type':'Button'},
            'launchmail': {'button': 'launchmail', 'description': 'Press (launchmail) button on keyboard', 'type':'Button'},
            'launchmediaselect': {'button': 'launchmediaselect', 'description': 'Press (launchmediaselect) button on keyboard', 'type':'Button'},
            'modechange': {'button': 'modechange', 'description': 'Press (modechange) button on keyboard', 'type':'Button'},
            'multiply': {'button': 'multiply', 'description': 'Press (multiply) button on keyboard', 'type':'Button'},
            'nexttrack': {'button': 'nexttrack', 'description': 'Press (nexttrack) button on keyboard', 'type':'Button'},
            'nonconvert': {'button': 'nonconvert', 'description': 'Press (nonconvert) button on keyboard', 'type':'Button'},
            'numlock': {'button': 'numlock', 'description': 'Press (numlock) button on keyboard', 'type':'Button'},
            'Key.page_down': {'button': 'pagedown', 'description': 'Press (pagedown) button on keyboard', 'type':'Button'},
            'Key.page_up': {'button': 'pageup', 'description': 'Press (pageup) button on keyboard', 'type':'Button'},
            'Key.pause': {'button': 'pause', 'description': 'Press (pause) button on keyboard', 'type':'Button'},
            'pgdn': {'button': 'pgdn', 'description': 'Press (pgdn) button on keyboard', 'type':'Button'},
            'pgup': {'button': 'pgup', 'description': 'Press (pgup) button on keyboard', 'type':'Button'},
            'playpause': {'button': 'playpause', 'description': 'Press (playpause) button on keyboard', 'type':'Button'},
            'prevtrack': {'button': 'prevtrack', 'description': 'Press (prevtrack) button on keyboard', 'type':'Button'},
            'print': {'button': 'print', 'description': 'Press (print) button on keyboard', 'type':'Button'},
            'Key.print_screen': {'button': 'printscreen', 'description': 'Press (printscreen) button on keyboard', 'type':'Button'},
            'prntscrn': {'button': 'prntscrn', 'description': 'Press (prntscrn) button on keyboard', 'type':'Button'},
            'return': {'button': 'return', 'description': 'Press (return) button on keyboard', 'type':'Button'},
            'Key.right': {'button': 'right', 'description': 'Press (right) button on keyboard', 'type':'Button'},
            'select': {'button': 'select', 'description': 'Press (select) button on keyboard', 'type':'Button'},
            'separator': {'button': 'separator', 'description': 'Press (separator) button on keyboard', 'type':'Button'},
            'Key.shift': {'button': 'shift', 'description': 'Press (shift) button on keyboard', 'type':'Button'},
            'Key.shift_l': {'button': 'shiftleft', 'description': 'Press (shiftleft) button on keyboard', 'type':'Button'},
            'Key.shift_r': {'button': 'shiftright', 'description': 'Press (shiftright) button on keyboard', 'type':'Button'},
            'sleep': {'button': 'sleep', 'description': 'Press (sleep) button on keyboard', 'type':'Button'},
            'Key.space': {'button': 'space', 'description': 'Press (space) button on keyboard', 'type':'Button'},
            'stop': {'button': 'stop', 'description': 'Press (stop) button on keyboard', 'type':'Button'},
            'subtract': {'button': 'subtract', 'description': 'Press (subtract) button on keyboard', 'type':'Button'},
            'Key.tab': {'button': 'tab', 'description': 'Press (tab) button on keyboard', 'type':'Button'},
            'Key.up': {'button': 'up', 'description': 'Press (up) button on keyboard', 'type':'Button'},
            'volumedown': {'button': 'volumedown', 'description': 'Press (volumedown) button on keyboard', 'type':'Button'},
            'volumemute': {'button': 'volumemute', 'description': 'Press (volumemute) button on keyboard', 'type':'Button'},
            'volumeup': {'button': 'volumeup', 'description': 'Press (volumeup) button on keyboard', 'type':'Button'},
            'win': {'button': 'win', 'description': 'Press (win) button on keyboard', 'type':'Button'},
            'Key.cmd': {'button': 'cmd', 'description': 'Press (cmd) button on keyboard', 'type':'Button'},
            'winleft': {'button': 'winleft', 'description': 'Press (winleft) button on keyboard', 'type':'Button'},
            'winright': {'button': 'winright', 'description': 'Press (winright) button on keyboard', 'type':'Button'},
            'command': {'button': 'command', 'description': 'Press (command) button on keyboard', 'type':'Button'},
            'option': {'button': 'option', 'description': 'Press (option) button on keyboard', 'type':'Button'},
            'optionleft': {'button': 'optionleft', 'description': 'Press (optionleft) button on keyboard', 'type':'Button'},
            'optionright': {'button': 'optionright', 'description': 'Press (optionright) button on keyboard', 'type':'Button'},
            'yen': {'button': 'yen', 'description': 'Press (yen) button on keyboard', 'type':'Button'},
            'hanguel': {'button': 'hanguel', 'description': 'Press (hanguel) button on keyboard', 'type':'Button'},
            'hangul': {'button': 'hangul', 'description': 'Press (hangul) button on keyboard', 'type':'Button'},
            'hanja': {'button': 'hanja', 'description': 'Press (hanja) button on keyboard', 'type':'Button'},
            'help': {'button': 'help', 'description': 'Press (help) button on keyboard', 'type':'Button'},
            'junja': {'button': 'junja', 'description': 'Press (junja) button on keyboard', 'type':'Button'},
            'kana': {'button': 'kana', 'description': 'Press (kana) button on keyboard', 'type':'Button'},
            'kanji': {'button': 'kanji', 'description': 'Press (kanji) button on keyboard', 'type':'Button'},

            '\t': {'button': '\t', 'description': 'Insert tab (four spaces)', 'type': 'Whitespace'},
            '\n': {'button': '\n', 'description': 'Insert newline (not like enter)', 'type': 'Whitespace'},
            '\r': {'button': '\r', 'description': 'Insert carriage return (set typing cursor in the beginning of the line)', 'type': 'Whitespace'},
        }

    def isKey(self, key):
        if key in self.keyboard_keys:
            return True
        return False

    def button(self, key):
        if key in self.keyboard_keys:
            return self.keyboard_keys[key]['button']
        else:
            return key

    def description(self, key):
        if key in self.keyboard_keys:
            return self.keyboard_keys[key]['description']
        return ''

    def type(self, key):
        if key in self.keyboard_keys:
            return self.keyboard_keys[key]['type']
        return key

KD = Keyboard()
